[package]
name = "letrs-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "letrs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
letrs = { version = "0.1.0", path = "../letrs" }
